
---
title: "Categorized Function List"
output: 
  rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Categorized Function List}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# ML algorithms

    * qeAdaBoost(): Ada Boosting, wraps Jousboost pkg

    * qeDeepnet(): wraps deepnet pkg

    * qeDT(): decision trees, wraps party pkg

    * qeGBoost(): gradient boosting, wraps gbm pkg

    * qeKNN(): k-Nearest Neighbors, wraps regtools pkg; includes
      predictor importance settings; allows linear interpolation within
      a bin

    * qeLASSO(): LASSO and ridge regression, wraps glmment pkg

    * qeLightGBoost(): gradient boosting, wraps lightgbm pkg

    * qeLin(): wraps R's lm()

    * qeLinKNN(): first fits qeLin(), followed by k-NN on the
      residuals to correct deviations from linearity

    * qeLogit(): wraps R's glm()

    * qeNeural(): wraps keras package, including CNN

    * qePolyLASSO(): LASSO/ridge applied to polynomial regression;
      wraps glmnet, polyreg pkgs

    * qePolyLin(): polynomial regression on linear models;
      uses Moore-Penrose inverse if overfitting; wraps polyreg pkg

    * qePolyLog(): polynomial regression on logistic models;
      wraps polyreg pkg

    * qeRF(): random forests, wraps randomforest pkg

    * qeRFgrf: random forests, wraps grf pkg; allows linear
      interpolation within a bin

    * qeRpart(): decision trees, wraps Rpart pkg; colorful tree plot

    * qeRFranger(): random forests, wraps ranger pkg

    * qeskRF(): random forests, wraps Python Scilearn pkg

    * qeskSVM(): SVM, wraps Python Scilearn pkg

    * qeSVM(): SVM, wraps e1071 pkg

    * qeSVMliquid(): SVM, wraps liquid SVM pkg

    * qeXGBoost() wraps the xgboost pkg

# Feature selection and model-fitting

    * doubleD(): computation and plotting for exploring Double Descent

    * plotClassesUMAP(): plot first two UMAP components,
      color-coding classes

    * plotPairedResiduals(): plot residuals against pairs of
      features

    * qeCompare():  compare the accuracy of various ML methods on a
      given dataset

    * qeFOCI(): fully nonparametric method for feature selection,
      wraps FOCI pkg

    * qeFT():  automated grid hyperparameter search, with
      Bonferroni-Dunn corrected standard errors

    * qeLASSO():  for fit and/or feature selection

    * qeLeaveOut1Var, qeLASSO, qeFOCI, qeFOCIrand,
      qeRFranger and qeKNN, all can be used for assessing or
      setting variable importance

    * qePCA():  find principal components, number specified by user,
      then fit the resulting model, according to qe* function
      specified by user

    * qeROC():  ROC computation and plotting, wraps pROC pkg

    * qeUMAP():  same as qePCA() but using UMAP

    * replicMeans(): (from regtools, included in qeML)
      averages output, e.g. testAcc, over many holdout sets

# Application-specific functions (elementary)

    * qeText()  text classification

    * qeTS():  time series

    * *image classification*:  Our imageClassR package uses qe
      functions for this.  (Under construction.)

# Prediction with missing values

    * qeLinMV(), qeLogitMV(), qeKNNMV(), associated predict() 
      generics for use with toweranNA pkg

# Utilities, exploratory tools

    * dataToTopLevels():  applies factorToTopLevels() to all
      factors in the given data frame

    * factorToTopLevels():  removes rare levels from a factor

    * levelCounts():  performs a census of levels for each R factor in
      the dataset

    * qeParallel():  apply "Software Alchemy" to parallelize
      qe functions

